[ERROR 2022-05-05 05:37:33,655] worker.py: 428  Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::MERA.__init__()[39m (pid=3478, ip=10.128.0.8)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/qc_whaley/dephased_ttn_project/mera/non_distributed_tunning/model_tuning.py", line 114, in setup
    self.model = Tuning_Model(data_path, digits, val_split, deph_p, num_anc, config, tune_config)
  File "/home/qc_whaley/dephased_ttn_project/mera/non_distributed_tunning/model_tuning.py", line 23, in __init__
    super().__init__(data_path, digits, val_split, deph_p, num_anc, -1, -1, config)
  File "/home/qc_whaley/dephased_ttn_project/mera/model.py", line 115, in __init__
    self.network = network.Network(num_pixels, deph_p, num_anc, init_std, lr, config)
  File "/home/qc_whaley/dephased_ttn_project/mera/network.py", line 29, in __init__
    self.kraus_ops_1_bd = self.construct_dephasing_multiqubit_kraus(self.num_out_qubits)
  File "/home/qc_whaley/dephased_ttn_project/mera/network.py", line 192, in construct_dephasing_multiqubit_kraus
    m1 = tf.cast(tf.math.sqrt((2 - self.deph_p) / 2), tf.complex64) * tf.eye(2, dtype=tf.complex64)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py", line 5326, in sqrt
    return gen_math_ops.sqrt(x, name)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10301, in sqrt
    _ops.raise_from_not_ok_status(e, name)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: failed to allocate memory [Op:Sqrt]
