[ERROR 2022-03-09 07:53:16,553] import_thread.py: 88  ImportThread: Connection closed by server.
